name: MiscKit CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'
  schedule:
    # run at 6AM & 6PM UTC
    - cron:  '0 6,18 * * *'

jobs:    
  Linux:
    name: MiscKit Linux Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: swift test --enable-test-discovery

  macOS:
    name: MiscKit macOS Tests
    runs-on: macos-11.0
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: swift test --enable-test-discovery

