name: MiscKit CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches:
      - '*'

jobs:    
  Linux:
    name: MiscKit Linux Tests
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Run tests
      run: swift test --enable-test-discovery

  #macOS:
  #  name: MiscKit macOS Tests
  #  runs-on: macos-latest
  #  steps:
  #  - uses: actions/checkout@v2
  #  - name: Run tests
  #    run: swift test --enable-test-discovery

